In [8]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/250.9 kB 660.6 kB/s eta 0:00:01
   -------------------------------- ------- 204.8/250.9 kB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 250.9/250.9 kB 2.2 MB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: C:\Users\hasebul\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

# Generate Evaluation Prompt

In [3]:
import pandas as pd

def load_data_from_excel(excel_path, sheet_name, column_mapping):
    """
    Loads data from a specified sheet in an Excel file.

    Args:
        excel_path (str): The file path for the Excel file.
        sheet_name (str): The name of the sheet to read from.
        column_mapping (dict): Maps template keys to Excel column names.
                               If a column name is None, a default value is used.

    Returns:
        list: A list of dictionaries, where each dictionary contains the data
              for one prompt (one row from the Excel sheet). Returns None on error.
    """
    print(f"Loading data from '{excel_path}' (Sheet: '{sheet_name}')...")
    try:
        df = pd.read_excel(excel_path, sheet_name=sheet_name)
        # Fill any empty cells with an empty string to avoid errors
        df.fillna("", inplace=True)
    except FileNotFoundError:
        print(f"Error: The file '{excel_path}' was not found.")
        return None
    except Exception as e:
        print(f"Error reading Excel file: {e}")
        return None

    all_data = []
    # Iterate over each row in the DataFrame
    for index, row in df.iterrows():
        data = {}
        print(f"  - Processing row {index + 1}...")
        for template_key, excel_column in column_mapping.items():
            if excel_column and excel_column in df.columns:
                # Get data from the specified excel column
                data[template_key] = row[excel_column]
            else:
                # Handle keys that are in the template but not mapped to an Excel column
                if template_key == "role_name":
                    data[template_key] = "Civilian"  # Default value
                elif template_key == "conversation":
                    data[template_key] = "[Insert Conversation Here]"  # Placeholder
                else:
                    # Provide a generic placeholder for other missing data
                    data[template_key] = f"[{template_key.replace('_', ' ').title()} Not Provided]"
        all_data.append(data)
    
    return all_data

In [14]:
EXCEL_FILE = "../../../data/de-escalation training dataset.xlsx"
SHEET_NAME = "synthesis_dataset"

# Map the placeholders in your template file to the column names in your Excel sheet.
# If a placeholder doesn't have a corresponding column, it will get a default value.
COLUMN_MAPPING = {
    "scenario_name": "Scenario_Title",
    "character_profile": "Scenario_Set_up",
    "profile": "Scenario_Character_Profile",
    "goal": "Scenario_recommendation_action",
    # --- Template keys not found in your provided column list ---
    # These will be filled with default/placeholder values.
    "triggers": None,
    "reaction": None,
    "role_name": None,
    "conversation": None,
}

# 1. Load the data from the Excel file
all_prompt_data = load_data_from_excel(EXCEL_FILE, SHEET_NAME, COLUMN_MAPPING)
print(all_prompt_data)

Loading data from '../../../data/de-escalation training dataset.xlsx' (Sheet: 'synthesis_dataset')...
  - Processing row 1...
  - Processing row 2...
  - Processing row 3...
  - Processing row 4...
  - Processing row 5...
  - Processing row 6...
  - Processing row 7...
  - Processing row 8...
  - Processing row 9...
  - Processing row 10...
  - Processing row 11...
  - Processing row 12...
  - Processing row 13...
  - Processing row 14...
  - Processing row 15...
  - Processing row 16...
  - Processing row 17...
  - Processing row 18...
  - Processing row 19...
  - Processing row 20...
  - Processing row 21...
  - Processing row 22...
  - Processing row 23...
  - Processing row 24...
  - Processing row 25...
  - Processing row 26...
  - Processing row 27...
  - Processing row 28...
  - Processing row 29...
  - Processing row 30...

C:\Users\hasebul\AppData\Local\Temp\ipykernel_12876\3634231618.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna("", inplace=True)

In [15]:
all_prompt_data

[{'scenario_name': 'Mike’s Bad Day',
  'character_profile': '1.Bartender (caller) briefing: \n        Greets officers say Mike has been drinking heavily for a couple of hours.\n        Explains Mike’s wife left him; he’s suicidal and possibly armed.\n2. Mike’s first statement: \n        “Please just leave me alone, I don’t want to talk to anybody right now!”\n',
  'profile': "Mike, 42, construction worker. Recently lost job, wife left 3 weeks ago. Depressed, drinking heavily.\nStates he has a gun and wants to die ('suicide by cop' risk). Can be talkative/cooperative\n if officer shows empathy and avoids triggers. Cusses almost every sentence. Likes cars and action movies. Becomes angry/hostile if communication is poor, authoritative, or focuses repeatedly on wife/job loss. Currently inside the 'River Bottoms' pub. Intoxicated.",
  'goal': '•\tMove to a tactically safe position (Distance + Cover = Time).\n•\tGet the bartender to a safe area (ideally outside) before contacting Mike.\n•\tHave lethal and less-lethal cover ready because Mike might be armed.\n',
  'triggers': '[Triggers Not Provided]',
  'reaction': '[Reaction Not Provided]',
  'role_name': 'Civilian',
  'conversation': '[Insert Conversation Here]'},
 {'scenario_name': 'Mike’s Bad Day',
  'character_profile': '1.Bartender (caller) briefing: \n        Greets officers say Mike has been drinking heavily for a couple of hours.\n        Explains Mike’s wife left him; he’s suicidal and possibly armed.\n2. Mike’s first statement: \n        “Please just leave me alone, I don’t want to talk to anybody right now!”\n',
  'profile': "Mike, 42, construction worker. Recently lost job, wife left 3 weeks ago. Depressed, drinking heavily.\nStates he has a gun and wants to die ('suicide by cop' risk). Can be talkative/cooperative\n if officer shows empathy and avoids triggers. Cusses almost every sentence. Likes cars and action movies. Becomes angry/hostile if communication is poor, authoritative, or focuses repeatedly on wife/job loss. Currently inside the 'River Bottoms' pub. Intoxicated.",
  'goal': '•\tMove to a tactically safe position (Distance + Cover = Time).\n•\tGet the bartender to a safe area (ideally outside) before contacting Mike.\n•\tHave lethal and less-lethal cover ready because Mike might be armed.\n',
  'triggers': '[Triggers Not Provided]',
  'reaction': '[Reaction Not Provided]',
  'role_name': 'Civilian',
  'conversation': '[Insert Conversation Here]'},
 {'scenario_name': 'Mike’s Bad Day',
  'character_profile': '1.Bartender (caller) briefing: \n        Greets officers say Mike has been drinking heavily for a couple of hours.\n        Explains Mike’s wife left him; he’s suicidal and possibly armed.\n2. Mike’s first statement: \n        “Please just leave me alone, I don’t want to talk to anybody right now!”\n',
  'profile': "Mike, 42, construction worker. Recently lost job, wife left 3 weeks ago. Depressed, drinking heavily.\nStates he has a gun and wants to die ('suicide by cop' risk). Can be talkative/cooperative\n if officer shows empathy and avoids triggers. Cusses almost every sentence. Likes cars and action movies. Becomes angry/hostile if communication is poor, authoritative, or focuses repeatedly on wife/job loss. Currently inside the 'River Bottoms' pub. Intoxicated.",
  'goal': '•\tMove to a tactically safe position (Distance + Cover = Time).\n•\tGet the bartender to a safe area (ideally outside) before contacting Mike.\n•\tHave lethal and less-lethal cover ready because Mike might be armed.\n',
  'triggers': '[Triggers Not Provided]',
  'reaction': '[Reaction Not Provided]',
  'role_name': 'Civilian',
  'conversation': '[Insert Conversation Here]'},
 {'scenario_name': 'Mike’s Bad Day',
  'character_profile': '1.Bartender (caller) briefing: \n        Greets officers say Mike has been drinking heavily for a couple of hours.\n        Explains Mike’s wife left him; he’s suicidal and possibly armed.\n2. Mike’s first statement: \n        “Please just leave me alone, I don’t want to talk to anybody right now!”\n',
  'profile': "Mike, 42, construction worker. Recently lost job, wife left 3 weeks ago. Depressed, drinking heavily.\nStates he has a gun and wants to die ('suicide by cop' risk). Can be talkative/cooperative\n if officer shows empathy and avoids triggers. Cusses almost every sentence. Likes cars and action movies. Becomes angry/hostile if communication is poor, authoritative, or focuses repeatedly on wife/job loss. Currently inside the 'River Bottoms' pub. Intoxicated.",
  'goal': '•\tMove to a tactically safe position (Distance + Cover = Time).\n•\tGet the bartender to a safe area (ideally outside) before contacting Mike.\n•\tHave lethal and less-lethal cover ready because Mike might be armed.\n',
  'triggers': '[Triggers Not Provided]',
  'reaction': '[Reaction Not Provided]',
  'role_name': 'Civilian',
  'conversation': '[Insert Conversation Here]'},
 {'scenario_name': 'Mike’s Bad Day',
  'character_profile': '1.Bartender (caller) briefing: \n        Greets officers say Mike has been drinking heavily for a couple of hours.\n        Explains Mike’s wife left him; he’s suicidal and possibly armed.\n2. Mike’s first statement: \n        “Please just leave me alone, I don’t want to talk to anybody right now!”\n',
  'profile': "Mike, 42, construction worker. Recently lost job, wife left 3 weeks ago. Depressed, drinking heavily.\nStates he has a gun and wants to die ('suicide by cop' risk). Can be talkative/cooperative\n if officer shows empathy and avoids triggers. Cusses almost every sentence. Likes cars and action movies. Becomes angry/hostile if communication is poor, authoritative, or focuses repeatedly on wife/job loss. Currently inside the 'River Bottoms' pub. Intoxicated.",
  'goal': '•\tMove to a tactically safe position (Distance + Cover = Time).\n•\tGet the bartender to a safe area (ideally outside) before contacting Mike.\n•\tHave lethal and less-lethal cover ready because Mike might be armed.\n',
  'triggers': '[Triggers Not Provided]',
  'reaction': '[Reaction Not Provided]',
  'role_name': 'Civilian',
  'conversation': '[Insert Conversation Here]'},
 {'scenario_name': 'Mike’s Bad Day',
  'character_profile': '1.Bartender (caller) briefing: \n        Greets officers say Mike has been drinking heavily for a couple of hours.\n        Explains Mike’s wife left him; he’s suicidal and possibly armed.\n2. Mike’s first statement: \n        “Please just leave me alone, I don’t want to talk to anybody right now!”\n',
  'profile': "Mike, 42, construction worker. Recently lost job, wife left 3 weeks ago. Depressed, drinking heavily.\nStates he has a gun and wants to die ('suicide by cop' risk). Can be talkative/cooperative\n if officer shows empathy and avoids triggers. Cusses almost every sentence. Likes cars and action movies. Becomes angry/hostile if communication is poor, authoritative, or focuses repeatedly on wife/job loss. Currently inside the 'River Bottoms' pub. Intoxicated.",
  'goal': '•        Move to a tactically safe position (Distance + Cover = Time).\n•        Get the bartender to a safe area (ideally outside) before contacting Mike.\n•        Have lethal and less-lethal cover ready because Mike might be armed.\n',
  'triggers': '[Triggers Not Provided]',
  'reaction': '[Reaction Not Provided]',
  'role_name': 'Civilian',
  'conversation': '[Insert Conversation Here]'},
 {'scenario_name': 'Suicidal Subject at City Bench',
  'character_profile': '1.        Officers see Jenny on the bench, knife against her throat, threatening self-harm.\n2.        Busy restaurant behind her (Heim BBQ), many bystanders possibly in the line of fire.\n3.        Officer/student should: \n               Establish distance and cover (e.g., behind a bench, a tree).\n               Prepare lethal and less-lethal force options.\n               Ensure bystanders/patrons are warned or moved from danger.\n',
  'profile': 'Jenny, distraught, holding kitchen knife to throat in public. Turning 40, recent breakup (boyfriend left for best friend), job loss imminent. Highly emotional, feeling hopeless, initially wants to be left alone. Risk of self-harm or charging if approached improperly.',
  'goal': '1.        Officer/student immediately recognizes the deadly threat (knife).\n2.        They create distance, use cover, plan lethal/less-lethal options, and account for the busy restaurant behind Jenny.\n3.        Use empathetic and calm communication from the start.\n4.        Jenny quickly responds positively: \n               Agrees to put down the knife.\n               Complies with going for a “Mental APP” (mental health evaluation).\n5.        Scenario ends with a successful, non-violent resolution.\n',
  'triggers': '[Triggers Not Provided]',
  'reaction': '[Reaction Not Provided]',
  'role_name': 'Civilian',
  'conversation': '[Insert Conversation Here]'},
 {'scenario_name': 'Suicidal Subject at City Bench',
  'character_profile': '1.        Officers see Jenny on the bench, knife against her throat, threatening self-harm.\n2.        Busy restaurant behind her (Heim BBQ), many bystanders possibly in the line of fire.\n3.        Officer/student should: \n               Establish distance and cover (e.g., behind a bench, a tree).\n               Prepare lethal and less-lethal force options.\n               Ensure bystanders/patrons are warned or moved from danger.\n',
  'profile': 'Jenny, distraught, holding kitchen knife to throat in public. Turning 40, recent breakup (boyfriend left for best friend), job loss imminent. Highly emotional, feeling hopeless, initially wants to be left alone. Risk of self-harm or charging if approached improperly.',
  'goal': '1.        Officer/student immediately recognizes the deadly threat (knife).\n2.        They create distance, use cover, plan lethal/less-lethal options, and account for the busy restaurant behind Jenny.\n3.        Use empathetic and calm communication from the start.\n4.        Jenny quickly responds positively: \n               Agrees to put down the knife.\n               Complies with going for a “Mental APP” (mental health evaluation).\n5.        Scenario ends with a successful, non-violent resolution.\n',
  'triggers': '[Triggers Not Provided]',
  'reaction': '[Reaction Not Provided]',
  'role_name': 'Civilian',
  'conversation': '[Insert Conversation Here]'},
 {'scenario_name': 'Suicidal Subject at City Bench',
  'character_profile': '1.        Officers see Jenny on the bench, knife against her throat, threatening self-harm.\n2.        Busy restaurant behind her (Heim BBQ), many bystanders possibly in the line of fire.\n3.        Officer/student should: \n               Establish distance and cover (e.g., behind a bench, a tree).\n               Prepare lethal and less-lethal force options.\n               Ensure bystanders/patrons are warned or moved from danger.\n',
  'profile': 'Jenny, distraught, holding kitchen knife to throat in public. Turning 40, recent breakup (boyfriend left for best friend), job loss imminent. Highly emotional, feeling hopeless, initially wants to be left alone. Risk of self-harm or charging if approached improperly.',
  'goal': '1.        Officer/student immediately recognizes the deadly threat (knife).\n2.        They create distance, use cover, plan lethal/less-lethal options, and account for the busy restaurant behind Jenny.\n3.        Use empathetic and calm communication from the start.\n4.        Jenny quickly responds positively: \n               Agrees to put down the knife.\n               Complies with going for a “Mental APP” (mental health evaluation).\n5.        Scenario ends with a successful, non-violent resolution.\n',
  'triggers': '[Triggers Not Provided]',
  'reaction': '[Reaction Not Provided]',
  'role_name': 'Civilian',
  'conversation': '[Insert Conversation Here]'},
 {'scenario_name': 'Suicidal Subject at City Bench',
  'character_profile': '1.        Officers see Jenny on the bench, knife against her throat, threatening self-harm.\n2.        Busy restaurant behind her (Heim BBQ), many bystanders possibly in the line of fire.\n3.        Officer/student should: \n               Establish distance and cover (e.g., behind a bench, a tree).\n               Prepare lethal and less-lethal force options.\n               Ensure bystanders/patrons are warned or moved from danger.\n',
  'profile': 'Jenny, distraught, holding kitchen knife to throat in public. Turning 40, recent breakup (boyfriend left for best friend), job loss imminent. Highly emotional, feeling hopeless, initially wants to be left alone. Risk of self-harm or charging if approached improperly.',
  'goal': '1.        Officer/student immediately recognizes the deadly threat (knife).\n2.        They create distance, use cover, plan lethal/less-lethal options, and account for the busy restaurant behind Jenny.\n3.        Use empathetic and calm communication from the start.\n4.        Jenny quickly responds positively: \n               Agrees to put down the knife.\n               Complies with going for a “Mental APP” (mental health evaluation).\n5.        Scenario ends with a successful, non-violent resolution.\n',
  'triggers': '[Triggers Not Provided]',
  'reaction': '[Reaction Not Provided]',
  'role_name': 'Civilian',
  'conversation': '[Insert Conversation Here]'},
 {'scenario_name': 'Suicidal Subject at City Bench',
  'character_profile': '1.        Officers see Jenny on the bench, knife against her throat, threatening self-harm.\n2.        Busy restaurant behind her (Heim BBQ), many bystanders possibly in the line of fire.\n3.        Officer/student should: \n               Establish distance and cover (e.g., behind a bench, a tree).\n               Prepare lethal and less-lethal force options.\n               Ensure bystanders/patrons are warned or moved from danger.\n',
  'profile': 'Jenny, distraught, holding kitchen knife to throat in public. Turning 40, recent breakup (boyfriend left for best friend), job loss imminent. Highly emotional, feeling hopeless, initially wants to be left alone. Risk of self-harm or charging if approached improperly.',
  'goal': '1.        Officer/student immediately recognizes the deadly threat (knife).\n2.        They create distance, use cover, plan lethal/less-lethal options, and account for the busy restaurant behind Jenny.\n3.        Use empathetic and calm communication from the start.\n4.        Jenny quickly responds positively: \n               Agrees to put down the knife.\n               Complies with going for a “Mental APP” (mental health evaluation).\n5.        Scenario ends with a successful, non-violent resolution.\n',
  'triggers': '[Triggers Not Provided]',
  'reaction': '[Reaction Not Provided]',
  'role_name': 'Civilian',
  'conversation': '[Insert Conversation Here]'},
 {'scenario_name': 'Suicidal Subject at City Bench',
  'character_profile': '1.        Officers see Jenny on the bench, knife against her throat, threatening self-harm.\n2.        Busy restaurant behind her (Heim BBQ), many bystanders possibly in the line of fire.\n3.        Officer/student should: \n               Establish distance and cover (e.g., behind a bench, a tree).\n               Prepare lethal and less-lethal force options.\n               Ensure bystanders/patrons are warned or moved from danger.\n',
  'profile': 'Jenny, distraught, holding kitchen knife to throat in public. Turning 40, recent breakup (boyfriend left for best friend), job loss imminent. Highly emotional, feeling hopeless, initially wants to be left alone. Risk of self-harm or charging if approached improperly.',
  'goal': '1.        Officer/student immediately recognizes the deadly threat (knife).\n2.        They create distance, use cover, plan lethal/less-lethal options, and account for the busy restaurant behind Jenny.\n3.        Use empathetic and calm communication from the start.\n4.        Jenny quickly responds positively: \n               Agrees to put down the knife.\n               Complies with going for a “Mental APP” (mental health evaluation).\n5.        Scenario ends with a successful, non-violent resolution.\n',
  'triggers': '[Triggers Not Provided]',
  'reaction': '[Reaction Not Provided]',
  'role_name': 'Civilian',
  'conversation': '[Insert Conversation Here]'},
 {'scenario_name': 'Teen Behaving Erratically at Science Museum',
  'character_profile': '1.        Officers see Jacob flailing and self-harming lightly (slapping himself).\n2.        The environment is chaotic, with bystanders urging officers to intervene forcefully.\n3.        Primary goal: \no        Determine if Jacob is armed.\no        Keep him away from busy roadway.\no        Use calm approach to avoid pushing him to run or escalate.\n',
  'profile': 'Jacob, teenager, exhibiting erratic behavior (yelping, arm flailing, self-slapping) likely due to distress. Possibly on the autism spectrum (stimming). Became separated from his mother in the museum, now scared, anxious, and overwhelmed by the crowd and noise.',
  'goal': '1.\tOfficer/student uses calm, reassuring tone from the outset.\n2.\tJacob yelps less, stops slapping himself, and starts talking about dinosaurs.\n3.\tHe apologizes for scaring everyone; he’s just scared and can’t find his mother.\n4.\tOfficer/student calls for assist officers to find Jacob’s mother at the Dino-Dig exhibit.\n5.\tOnce mother arrives, Jacob calms completely and the two reunite.\n6.\tMother thanks officers and explains Jacob is autistic: \no\tHe uses “stimming” to self-soothe.\no\tBoth mother and Jacob leave hand in hand.\n7.\tPositive resolution.\n',
  'triggers': '[Triggers Not Provided]',
  'reaction': '[Reaction Not Provided]',
  'role_name': 'Civilian',
  'conversation': '[Insert Conversation Here]'},
 {'scenario_name': 'Teen Behaving Erratically at Science Museum',
  'character_profile': '1.\tOfficers see Jacob flailing and self-harming lightly (slapping himself).\n2.\tThe environment is chaotic, with bystanders urging officers to intervene forcefully.\n3.\tPrimary goal: \no\tDetermine if Jacob is armed.\no\tKeep him away from busy roadway.\no\tUse calm approach to avoid pushing him to run or escalate.\n',
  'profile': 'Jacob, teenager, exhibiting erratic behavior (yelping, arm flailing, self-slapping) likely due to distress. Possibly on the autism spectrum (stimming). Became separated from his mother in the museum, now scared, anxious, and overwhelmed by the crowd and noise.',
  'goal': '1.\tOfficer/student uses calm, reassuring tone from the outset.\n2.\tJacob yelps less, stops slapping himself, and starts talking about dinosaurs.\n3.\tHe apologizes for scaring everyone; he’s just scared and can’t find his mother.\n4.\tOfficer/student calls for assist officers to find Jacob’s mother at the Dino-Dig exhibit.\n5.\tOnce mother arrives, Jacob calms completely and the two reunite.\n6.\tMother thanks officers and explains Jacob is autistic: \no\tHe uses “stimming” to self-soothe.\no\tBoth mother and Jacob leave hand in hand.\n7.\tPositive resolution.\n',
  'triggers': '[Triggers Not Provided]',
  'reaction': '[Reaction Not Provided]',
  'role_name': 'Civilian',
  'conversation': '[Insert Conversation Here]'},
 {'scenario_name': 'Teen Behaving Erratically at Science Museum',
  'character_profile': '1.\tOfficers see Jacob flailing and self-harming lightly (slapping himself).\n2.\tThe environment is chaotic, with bystanders urging officers to intervene forcefully.\n3.\tPrimary goal: \no\tDetermine if Jacob is armed.\no\tKeep him away from busy roadway.\no\tUse calm approach to avoid pushing him to run or escalate.\n',
  'profile': 'Jacob, teenager, exhibiting erratic behavior (yelping, arm flailing, self-slapping) likely due to distress. Possibly on the autism spectrum (stimming). Became separated from his mother in the museum, now scared, anxious, and overwhelmed by the crowd and noise.',

In [17]:
# import os
# # This script requires the pandas and openpyxl libraries.
# # You can install them by running: pip install pandas openpyxl
# import pandas as pd

# def load_data_from_excel(excel_path, sheet_name, column_mapping):
#     """
#     Loads data from a specified sheet in an Excel file.

#     Args:
#         excel_path (str): The file path for the Excel file.
#         sheet_name (str): The name of the sheet to read from.
#         column_mapping (dict): Maps template keys to Excel column names.
#                                If a column name is None, a default value is used.

#     Returns:
#         list: A list of dictionaries, where each dictionary contains the data
#               for one prompt (one row from the Excel sheet). Returns None on error.
#     """
#     print(f"Loading data from '{excel_path}' (Sheet: '{sheet_name}')...")
#     try:
#         df = pd.read_excel(excel_path, sheet_name=sheet_name)
#         # Fill any empty cells with an empty string to avoid errors
#         df.fillna("", inplace=True)
#     except FileNotFoundError:
#         print(f"Error: The file '{excel_path}' was not found.")
#         return None
#     except Exception as e:
#         print(f"Error reading Excel file: {e}")
#         return None

#     all_data = []
#     # Iterate over each row in the DataFrame
#     for index, row in df.iterrows():
#         data = {}
#         print(f"  - Processing row {index + 1}...")
#         for template_key, excel_column in column_mapping.items():
#             if excel_column and excel_column in df.columns:
#                 # Get data from the specified excel column
#                 data[template_key] = row[excel_column]
#             else:
#                 # Handle keys that are in the template but not mapped to an Excel column
#                 if template_key == "role_name":
#                     data[template_key] = "Civilian"  # Default value
#                 elif template_key == "conversation":
#                     data[template_key] = "[Insert Conversation Here]"  # Placeholder
#                 else:
#                     # Provide a generic placeholder for other missing data
#                     data[template_key] = f"[{template_key.replace('_', ' ').title()} Not Provided]"
#         all_data.append(data)
    
#     return all_data

def generate_prompt(template_path, data):
    """
    Generates a complete prompt by replacing placeholders in a template with data.

    Args:
        template_path (str): The file path for the prompt template.
        data (dict): A dictionary containing the data to fill in the template.

    Returns:
        str: The completed prompt with all placeholders replaced, or an error message.
    """
    print(f"\nReading prompt template from '{template_path}'...")
    try:
        with open(template_path, 'r', encoding='utf-8') as f:
            template = f.read()
        
        # Use the format method with the data dictionary to replace placeholders
        # The **data syntax unpacks the dictionary into keyword arguments
        completed_prompt = template.format(**data)
        return completed_prompt
    except FileNotFoundError:
        return f"Error: Template file not found at '{template_path}'"
    except KeyError as e:
        return f"Error: A key is missing in the data dictionary: {e}. Make sure all placeholders in the template are in the column_mapping."
    except Exception as e:
        return f"An unexpected error occurred: {e}"

if __name__ == "__main__":
    # --- Configuration ---
    TEMPLATE_FILE = "prompt_template.txt"
    EXCEL_FILE = "../../../data/de-escalation training dataset.xlsx"
    SHEET_NAME = "synthesis_dataset"

    # Map the placeholders in your template file to the column names in your Excel sheet.
    # If a placeholder doesn't have a corresponding column, it will get a default value.
    COLUMN_MAPPING = {
        "scenario_name": "Scenario_Title",
        "character_profile": "Scenario_Set_up",
        "profile": "Scenario_Character_Profile",
        "goal": "Scenario_recommendation_action",
        # --- Template keys not found in your provided column list ---
        # These will be filled with default/placeholder values.
        "triggers": None,
        "reaction": None,
        "role_name": None,
        "conversation": None,
    }

    # 1. Load the data from the Excel file
    all_prompt_data = load_data_from_excel(EXCEL_FILE, SHEET_NAME, COLUMN_MAPPING)

    if all_prompt_data:
        print(f"\nSuccessfully loaded data for {len(all_prompt_data)} prompts.")
        # 2. Generate a prompt for each row of data from the Excel file
        for i, prompt_data in enumerate(all_prompt_data, 1):
            final_prompt = generate_prompt(TEMPLATE_FILE, prompt_data)

            # 3. Print the final, generated prompt
            print("\n" + "="*50)
            print(f"      GENERATED PROMPT #{i}")
            print("="*50 + "\n")
            print(final_prompt)
            
            # 4. Save the generated prompt to a uniquely named file
            scenario_name_safe = str(prompt_data.get('scenario_name', f'prompt_{i}')).replace(' ', '_').replace('/', '_')
            output_filename = f"generated_prompt_{scenario_name_safe}.txt"
            
            try:
                with open(output_filename, "w", encoding="utf-8") as f:
                    f.write(final_prompt)
                print("\n" + "="*50)
                print(f"Prompt #{i} has been saved to '{output_filename}'")
                print("="*50)
            except Exception as e:
                print(f"\nError saving file '{output_filename}': {e}")

Loading data from '../../../data/de-escalation training dataset.xlsx' (Sheet: 'synthesis_dataset')...
  - Processing row 1...
  - Processing row 2...
  - Processing row 3...
  - Processing row 4...
  - Processing row 5...
  - Processing row 6...
  - Processing row 7...
  - Processing row 8...
  - Processing row 9...
  - Processing row 10...
  - Processing row 11...
  - Processing row 12...
  - Processing row 13...
  - Processing row 14...
  - Processing row 15...
  - Processing row 16...
  - Processing row 17...
  - Processing row 18...
  - Processing row 19...
  - Processing row 20...
  - Processing row 21...
  - Processing row 22...
  - Processing row 23...
  - Processing row 24...
  - Processing row 25...
  - Processing row 26...
  - Processing row 27...
  - Processing row 28...
  - Processing row 29...
  - Processing row 30...

Successfully loaded data for 30 prompts.

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #1
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #1 has been saved to 'generated_prompt_Mike’s_Bad_Day.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #2
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #2 has been saved to 'generated_prompt_Mike’s_Bad_Day.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #3
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #3 has been saved to 'generated_prompt_Mike’s_Bad_Day.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #4
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #4 has been saved to 'generated_prompt_Mike’s_Bad_Day.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #5
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #5 has been saved to 'generated_prompt_Mike’s_Bad_Day.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #6
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #6 has been saved to 'generated_prompt_Mike’s_Bad_Day.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #7
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #7 has been saved to 'generated_prompt_Suicidal_Subject_at_City_Bench.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #8
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #8 has been saved to 'generated_prompt_Suicidal_Subject_at_City_Bench.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #9
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #9 has been saved to 'generated_prompt_Suicidal_Subject_at_City_Bench.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #10
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #10 has been saved to 'generated_prompt_Suicidal_Subject_at_City_Bench.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #11
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #11 has been saved to 'generated_prompt_Suicidal_Subject_at_City_Bench.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #12
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #12 has been saved to 'generated_prompt_Suicidal_Subject_at_City_Bench.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #13
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #13 has been saved to 'generated_prompt_Teen_Behaving_Erratically_at_Science_Museum.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #14
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #14 has been saved to 'generated_prompt_Teen_Behaving_Erratically_at_Science_Museum.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #15
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #15 has been saved to 'generated_prompt_Teen_Behaving_Erratically_at_Science_Museum.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #16
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #16 has been saved to 'generated_prompt_Teen_Behaving_Erratically_at_Science_Museum.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #17
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #17 has been saved to 'generated_prompt_Teen_Behaving_Erratically_at_Science_Museum.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #18
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #18 has been saved to 'generated_prompt_Teen_Behaving_Erratically_at_Science_Museum.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #19
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #19 has been saved to 'generated_prompt_Angry_Veteran.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #20
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #20 has been saved to 'generated_prompt_Angry_Veteran.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #21
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #21 has been saved to 'generated_prompt_Angry_Veteran.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #22
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #22 has been saved to 'generated_prompt_Angry_Veteran.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #23
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #23 has been saved to 'generated_prompt_Angry_Veteran.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #24
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #24 has been saved to 'generated_prompt_Angry_Veteran.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #25
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #25 has been saved to 'generated_prompt_Suicidal_Domestic_Disturbance.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #26
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #26 has been saved to 'generated_prompt_Suicidal_Domestic_Disturbance.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #27
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #27 has been saved to 'generated_prompt_Suicidal_Domestic_Disturbance.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #28
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #28 has been saved to 'generated_prompt_Suicidal_Domestic_Disturbance.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #29
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #29 has been saved to 'generated_prompt_Suicidal_Domestic_Disturbance.txt'
==================================================

Reading prompt template from 'prompt_template.txt'...

==================================================
      GENERATED PROMPT #30
==================================================

Error: Template file not found at 'prompt_template.txt'

==================================================
Prompt #30 has been saved to 'generated_prompt_Suicidal_Domestic_Disturbance.txt'
==================================================

C:\Users\hasebul\AppData\Local\Temp\ipykernel_12876\3634231618.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna("", inplace=True)

In [5]:
excel_path = "../../../data/de-escalation training dataset.xlsx"
sheet_1_name = "synthesis_dataset"
sheet_2_name = "Data_with_negative_example"

In [14]:
df = pd.read_excel(excel_path, sheet_name=sheet_1_name)
df

,id,Scenario_Number,Scenario_Title,Scenario_Context,Scenario_Set_up,Scenario_Character_Profile,Scenario_recommendation_action,de_escalation_outccome,de_escalation_score,Conversation,is_ai_generated,conversation_generator,Prompt for Generation
0,1.0,1,Mike’s Bad Day,"Units respond to River Bottoms Pub, reference ...",1.Bartender (caller) briefing: \n Greet...,"Mike, 42, construction worker. Recently lost j...",•\tMove to a tactically safe position (Distanc...,Ideal,100,Officer: Hey there. My name is Chris. I'm with...,yes,gemeni 2.5 pro,NaN
1,2.0,1,Mike’s Bad Day,"Units respond to River Bottoms Pub, reference ...",1.Bartender (caller) briefing: \n Greet...,"Mike, 42, construction worker. Recently lost j...",•\tMove to a tactically safe position (Distanc...,Partial,-20,"Officer: Mike, police department. Step away fr...",yes,gemeni 2.5 pro,NaN
2,3.0,1,Mike’s Bad Day,"Units respond to River Bottoms Pub, reference ...",1.Bartender (caller) briefing: \n Greet...,"Mike, 42, construction worker. Recently lost j...",•\tMove to a tactically safe position (Distanc...,Failure,-100,"Officer: Police! Mike, show me your hands and ...",yes,gemeni 2.5 pro,NaN
3,4.0,1,Mike’s Bad Day,"Units respond to River Bottoms Pub, reference ...",1.Bartender (caller) briefing: \n Greet...,"Mike, 42, construction worker. Recently lost j...",•\tMove to a tactically safe position (Distanc...,Ideal,100,"Officer: Mike, right? I’m Dan. I’m just here t...",yes,chatgpt,NaN
4,5.0,1,Mike’s Bad Day,"Units respond to River Bottoms Pub, reference ...",1.Bartender (caller) briefing: \n Greet...,"Mike, 42, construction worker. Recently lost j...",•\tMove to a tactically safe position (Distanc...,Partial,30,"Officer: Evening, Mike. Name’s Dan. I’m not he...",yes,chatgpt,NaN
5,6.0,1,Mike’s Bad Day,"Units respond to River Bottoms Pub, reference ...",1.Bartender (caller) briefing: \n Greet...,"Mike, 42, construction worker. Recently lost j...",• Move to a tactically safe position (D...,Failure,-100,"Officer: Hey Mike, I’m Dan. I just came in to ...",yes,chatgpt,NaN
6,7.0,2,Suicidal Subject at City Bench,• Location: A bench in front of “Heim B...,"1. Officers see Jenny on the bench, kni...","Jenny, distraught, holding kitchen knife to th...",1. Officer/student immediately recogniz...,Ideal,100,"Officer: Hello, my name is Alex. I can see you...",yes,gemeni 2.5 pro,NaN
7,8.0,2,Suicidal Subject at City Bench,•\tLocation: A bench in front of “Heim Barbequ...,"1. Officers see Jenny on the bench, kni...","Jenny, distraught, holding kitchen knife to th...",1. Officer/student immediately recogniz...,Partial,-10,"Officer: Jenny, my name is Officer Williams. I...",yes,gemeni 2.5 Flash,NaN
8,9.0,2,Suicidal Subject at City Bench,•\tLocation: A bench in front of “Heim Barbequ...,"1. Officers see Jenny on the bench, kni...","Jenny, distraught, holding kitchen knife to th...",1. Officer/student immediately recogniz...,Failure,-100,"Officer: Ma'am, you need to calm down. Let's t...",yes,gemeni 2.5 Flash,NaN
9,10.0,2,Suicidal Subject at City Bench,•\tLocation: A bench in front of “Heim Barbequ...,"1. Officers see Jenny on the bench, kni...","Jenny, distraught, holding kitchen knife to th...",1. Officer/student immediately recogniz...,Ideal,100,"Officer: Hey, Jenny. My name’s Dan. I’m gonna ...",yes,chatgpt,NaN
10,11.0,2,Suicidal Subject at City Bench,•\tLocation: A bench in front of “Heim Barbequ...,"1. Officers see Jenny on the bench, kni...","Jenny, distraught, holding kitchen knife to th...",1. Officer/student immediately recogniz...,Partial,10,"Officer: Jenny, my name’s Dan. I’m staying rig...",yes,chatgpt,NaN
11,NaN,2,Suicidal Subject at City Bench,•\tLocation: A bench in front of “Heim Barbequ...,"1. Officers see Jenny on the bench, kni...","Jenny, distraught, holding kitchen knife to th...",1. Officer/student immediately recogniz...,Failure,-100,"Officer: Jenny, my name’s Officer Daniels. I d...",yes,chatgpt,NaN
12,NaN,3,Teen Behaving Erratically at Science Museum,• Officers dispatched to the Fort Worth...,1. Officers see Jacob flailing and self...,"Jacob, teenager, exhibiting erratic behavior (...","1.\tOfficer/student uses calm, reassuring tone...",Ideal,100,Officer: Hey. My name is Officer Evans. I'm ju...,yes,gemeni 2.5 Flash,NaN
13,NaN,3,Teen Behaving Erratically at Science Museum,• Officers dispatched to the Fort Worth...,1.\tOfficers see Jacob flailing and self-harmi...,"Jacob, teenager, exhibiting erratic behavior (...","1.\tOfficer/student uses calm, reassuring tone...",Partial,10,Officer: Hey. My name is Officer Evans. Can yo...,yes,gemeni 2.5 Flash,NaN
14,NaN,3,Teen Behaving Erratically at Science Museum,• Officers dispatched to the Fort Worth...,1.\tOfficers see Jacob flailing and self-harmi...,"Jacob, teenager, exhibiting erratic behavior (...","1.\tOfficer/student uses calm, reassuring tone...",Failure,-100,Jacob: Leave me the fuck alone! Get away from ...,yes,gemeni 2.5 Flash,NaN
15,NaN,3,Teen Behaving Erratically at Science Museum,• Officers dispatched to the Fort Worth...,1.\tOfficers see Jacob flailing and self-harmi...,"Jacob, teenager, exhibiting erratic behavior (...","1.\tOfficer/student uses calm, reassuring tone...",Ideal,100,"Officer: Hey there, buddy, I’m Officer Lee. Yo...",yes,chatgpt,NaN
16,NaN,3,Teen Behaving Erratically at Science Museum,• Officers dispatched to the Fort Worth...,1.\tOfficers see Jacob flailing and self-harmi...,"Jacob, teenager, exhibiting erratic behavior (...","1.\tOfficer/student uses calm, reassuring tone...",Partial,20,"Officer: Hey Jacob, my name’s Officer Harris. ...",yes,chatgpt,NaN
17,NaN,3,Teen Behaving Erratically at Science Museum,• Officers dispatched to the Fort Worth...,1.\tOfficers see Jacob flailing and self-harmi...,"Jacob, teenager, exhibiting erratic behavior (...","1.\tOfficer/student uses calm, reassuring tone...",Failure,-100,"Officer: Hey Jacob, my name’s Officer Thompson...",yes,chatgpt,NaN
18,NaN,4,Angry Veteran,• Officers dispatched to Fort Worth Eas...,1. Ricardo shouts: \no “Why are ...,"Ricardo, veteran, angry and highly paranoid ab...",1.\tOfficer/student calmly speaks with Ricardo...,Ideal,100,Ricardo: This is all a goddamn lie! You think ...,yes,gemeni 2.5 - Flash,NaN
19,NaN,4,Angry Veteran,• Officers dispatched to Fort Worth Eas...,1. Ricardo shouts: \no “Why are ...,"Ricardo, veteran, angry and highly paranoid ab...",1.\tOfficer/student calmly speaks with Ricardo...,Partial,20,Ricardo: This whole damn thing is a sham! Don'...,yes,gemeni 2.5 - Flash,NaN
20,NaN,4,Angry Veteran,• Officers dispatched to Fort Worth Eas...,1. Ricardo shouts: \no “Why are ...,"Ricardo, veteran, angry and highly paranoid ab...",1.\tOfficer/student calmly speaks with Ricardo...,Failure,-100,Ricardo: This whole damn thing is a sham! Don'...,yes,gemeni 2.5 - Flash,NaN
21,NaN,4,Angry Veteran,• Officers dispatched to Fort Worth Eas...,1. Ricardo shouts: \no “Why are ...,"Ricardo, veteran, angry and highly paranoid ab...",1.\tOfficer/student calmly speaks with Ricardo...,Ideal,100,"Officer: Hey sir, I’m Officer Martinez. I see ...",yes,chagpt,NaN
22,NaN,4,Angry Veteran,• Officers dispatched to Fort Worth Eas...,1. Ricardo shouts: \no “Why are ...,"Ricardo, veteran, angry and highly paranoid ab...",1.\tOfficer/student calmly speaks with Ricardo...,Partial,30,"Officer: Hey Ricardo, I’m Officer Daniels. I s...",yes,chagpt,NaN
23,NaN,4,Angry Veteran,• Officers dispatched to Fort Worth Eas...,1. Ricardo shouts: \no “Why are ...,"Ricardo, veteran, angry and highly paranoid ab...",1.\tOfficer/student calmly speaks with Ricardo...,Failure,-100,"Officer: Ricardo, I’m Officer Blake. Step away...",yes,chagpt,NaN
24,NaN,5,Suicidal Domestic Disturbance,• Officers dispatched to a home after a...,1.\tBecky meets officers: \no\tSays William ti...,"William, acutely suicidal, rope around neck, s...",1.\tOfficer/student immediately recognizes no ...,Ideal,100,William: Just get out! I don't want you here! ...,yes,gemeni 2.5 - Flash,NaN
25,NaN,5,Suicidal Domestic Disturbance,•\tOfficers dispatched to a home after a woman...,1.\tBecky meets officers: \no\tSays William ti...,"William, acutely suicidal, rope around neck, s...",1.\tOfficer/student immediately recognizes no ...,Partial,20,William: Get the fuck out of here! I told you ...,yes,gemeni 2.5 - Flash,NaN
26,NaN,5,Suicidal Domestic Disturbance,•\tOfficers dispatched to a home after a woman...,1.\tBecky meets officers: \no\tSays William ti...,"William, acutely suicidal, rope around neck, s...",1.\tOfficer/student immediately recognizes no ...,Failure,-100,William: Just get the fuck out of here! I don'...,yes,gemeni 2.5 - Flash,NaN
27,NaN,5,Suicidal Domestic Disturbance,•\tOfficers dispatched to a home after a woman...,1.\tBecky meets officers: \no\tSays William ti...,"William, acutely suicidal, rope around neck, s...",1.\tOfficer/student immediately recognizes no ...,Ideal,100,"Officer: William, my name’s Officer Harris. I’...",yes,chagpt,NaN
28,NaN,5,Suicidal Domestic Disturbance,•\tOfficers dispatched to a home after a woman...,1.\tBecky meets officers: \no\tSays William ti...,"William, acutely suicidal, rope around neck, s...",1.\tOfficer/student immediately recognizes no ...,Partial,20,"Officer: William, my name’s Officer Daniels. I...",yes,chagpt,NaN
29,NaN,5,Suicidal Domestic Disturbance,•\tOfficers dispatched to a home after a woman...,1.\tBecky meets officers: \no\tSays William ti...,"William, acutely suicidal, rope around neck, s...",1.\tOfficer/student immediately recognizes no ...,Failure,-100,"Officer: William, this is Officer Grant. Step ...",yes,chagpt,NaN

In [11]:
import openpyxl

In [15]:
workbook = openpyxl.load_workbook(excel_path, data_only=True)

In [16]:
workbook

In [13]:
df = pd.read_excel(workbook, sheet_name=sheet_1_name)
df

ValueError: Invalid file path or buffer object type: <class 'openpyxl.workbook.workbook.Workbook'>

In [17]:
import pandas as pd
print(pd.__version__)

2.3.2

In [18]:
print(openpyxl.__version__)

3.1.5

In [20]:
df2 = pd.read_excel(excel_path, sheet_name=sheet_2_name, engine='openpyxl', engine_kwargs={'data_only': True})
df2.head(30)

,id,de_escalation_outccome,Conversation,conversation_generator,look_Real,Origin
0,1.0,Ideal,Officer: Hey there. My name is Chris. I'm with...,gemeni 2.5 pro,1,1.0
1,2.0,Partial,"Officer: Mike, police department. Step away fr...",gemeni 2.5 pro,1,NaN
2,3.0,Failure,"Officer: Police! Mike, show me your hands and ...",gemeni 2.5 pro,1,NaN
3,4.0,Ideal,"Officer: Mike, right? I’m Dan. I’m just here t...",chatgpt,1,NaN
4,5.0,Partial,"Officer: Evening, Mike. Name’s Dan. I’m not he...",chatgpt,1,NaN
5,6.0,Failure,"Officer: Hey Mike, I’m Dan. I just came in to ...",chatgpt,1,NaN
6,7.0,Ideal,"Officer: Hello, my name is Alex. I can see you...",gemeni 2.5 pro,1,NaN
7,8.0,Partial,"Officer: Jenny, my name is Officer Williams. I...",gemeni 2.5 Flash,1,NaN
8,9.0,Failure,"Officer: Ma'am, you need to calm down. Let's t...",gemeni 2.5 Flash,1,NaN
9,10.0,Ideal,"Officer: Hey, Jenny. My name’s Dan. I’m gonna ...",chatgpt,1,NaN
10,11.0,Partial,"Officer: Jenny, my name’s Dan. I’m staying rig...",chatgpt,1,NaN
11,NaN,Failure,"Officer: Jenny, my name’s Officer Daniels. I d...",chatgpt,1,NaN
12,NaN,Ideal,Officer: Hey. My name is Officer Evans. I'm ju...,gemeni 2.5 Flash,1,NaN
13,NaN,Partial,Officer: Hey. My name is Officer Evans. Can yo...,gemeni 2.5 Flash,1,NaN
14,NaN,Failure,Jacob: Leave me the fuck alone! Get away from ...,gemeni 2.5 Flash,1,NaN
15,NaN,Ideal,"Officer: Hey there, buddy, I’m Officer Lee. Yo...",chatgpt,1,NaN
16,NaN,Partial,"Officer: Hey Jacob, my name’s Officer Harris. ...",chatgpt,1,NaN
17,NaN,Failure,"Officer: Hey Jacob, my name’s Officer Thompson...",chatgpt,1,NaN
18,NaN,Ideal,Ricardo: This is all a goddamn lie! You think ...,gemeni 2.5 - Flash,1,NaN
19,NaN,Partial,Ricardo: This whole damn thing is a sham! Don'...,gemeni 2.5 - Flash,1,NaN
20,NaN,Failure,Ricardo: This whole damn thing is a sham! Don'...,gemeni 2.5 - Flash,1,NaN
21,NaN,Ideal,"Officer: Hey sir, I’m Officer Martinez. I see ...",chagpt,1,NaN
22,NaN,Partial,"Officer: Hey Ricardo, I’m Officer Daniels. I s...",chagpt,1,NaN
23,NaN,Failure,"Officer: Ricardo, I’m Officer Blake. Step away...",chagpt,1,NaN
24,NaN,Ideal,William: Just get out! I don't want you here! ...,gemeni 2.5 - Flash,1,NaN
25,NaN,Partial,William: Get the fuck out of here! I told you ...,gemeni 2.5 - Flash,1,NaN
26,NaN,Failure,William: Just get the fuck out of here! I don'...,gemeni 2.5 - Flash,1,NaN
27,NaN,Ideal,"Officer: William, my name’s Officer Harris. I’...",chagpt,1,NaN
28,NaN,Partial,"Officer: William, my name’s Officer Daniels. I...",chagpt,1,NaN
29,NaN,Failure,"Officer: William, this is Officer Grant. Step ...",chagpt,1,NaN

In [ ]:
%pip install pandas openpyxl jupyterlab

In [21]:
import pandas as pd
import openpyxl
import sys

print("--- FINAL DIAGNOSTICS ---")
try:
    print(f"Python Executable Being Used: {sys.executable}")
    print(f"Pandas Version Loaded: {pd.__version__}")
    print(f"Openpyxl Version Loaded: {openpyxl.__version__}")

    # Now, let's try the correct code again
    # excel_path = 'your_file.xlsx'  # Make sure this path is correct
    # sheet_2_name = 'Sheet1'         # Make sure this is correct

    # df2 = pd.read_excel(excel_path, sheet_name=sheet_2_name, engine='openpyxl', engine_kwargs={'data_only': True})
    # print("\nSUCCESS: File read correctly.")

except Exception as e:
    print(f"\nERROR: The script failed as expected.")
    print(f"ERROR DETAILS: {e}")

print("---------------------------")

--- FINAL DIAGNOSTICS ---
Python Executable Being Used: C:\Users\hasebul\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe
Pandas Version Loaded: 2.3.2
Openpyxl Version Loaded: 3.1.5
---------------------------

In [ ]:
import os
import sys
import importlib.util
# This script requires the pandas and openpyxl libraries.
# You can install them by running: pip install pandas openpyxl
import pandas as pd

def load_data_from_excel(excel_path, sheet_1_name, column_mapping, sheet_2_name):
    """
    Loads data from a specified sheet in an Excel file.

    Args:
        excel_path (str): The file path for the Excel file.
        sheet_1_name (str): The name of the sheet 1 to read from.
        column_mapping (dict): Maps template keys to Excel column names.
                               If a column name is None, a default value is used.
        sheet_2_name (str): The name of the sheet 2 to read from.                       

    Returns:
        list: A list of dictionaries, where each dictionary contains the data
              for one prompt (one row from the Excel sheet). Returns None on error.
    """
    print(f"Loading data from '{excel_path}' (Sheet: '{sheet_1_name}')...")
    try:
        df = pd.read_excel(excel_path, sheet_name=sheet_1_name)
        df_2 = pd.read_excel(excel_path, sheet_name=sheet_2_name)
        # Fill any empty cells with an empty string to avoid errors
        # df.fillna("", inplace=True)
    except FileNotFoundError:
        print(f"Error: The file '{excel_path}' was not found.")
        return None
    except Exception as e:
        print(f"Error reading Excel file: {e}")
        return None

    all_data = []
    # Iterate over each row in the DataFrame
    for index, row in df.iterrows():
        data = {}
        print(f"  - Processing row {index + 1}...")
        for template_key, excel_column in column_mapping.items():
            if excel_column and excel_column in df.columns:
                # Get data from the specified excel column
                value = row[excel_column]
                # Ensure value is a string and strip leading/trailing whitespace
                data[template_key] = str(value).strip()
            else:
                # Handle keys that are in the template but not mapped to an Excel column
                if template_key == "role_name":
                    data[template_key] = "Civilian"  # Default value
                elif template_key == "conversation":
                    data[template_key] = "[Insert Conversation Here]"  # Placeholder
                else:
                    # Provide a generic placeholder for other missing data
                    data[template_key] = f"[{template_key.replace('_', ' ').title()} Not Provided]"
        all_data.append(data)
    
    return all_data

def generate_prompt(template_path, data):
    """
    Generates a complete prompt by replacing placeholders in a template with data.
    The template is loaded from a 'prompt' variable within the Python file specified.

    Args:
        template_path (str): The file path for the prompt template Python file.
        data (dict): A dictionary containing the data to fill in the template.

    Returns:
        str: The completed prompt with all placeholders replaced, or an error message.
    """
    print(f"\nLoading prompt template from variable in '{template_path}'...")
    try:
        # Create a module name from the file path
        module_name = os.path.splitext(os.path.basename(template_path))[0]
        
        # Create a module spec from the file path
        spec = importlib.util.spec_from_file_location(module_name, template_path)
        if spec is None:
            return f"Error: Could not create module spec for '{template_path}'. Check if the file exists and is accessible."
            
        # Create a new module based on the spec
        prompt_module = importlib.util.module_from_spec(spec)
        
        # Execute the module in its own namespace
        spec.loader.exec_module(prompt_module)
        
        # Get the 'prompt' variable from the module
        template = getattr(prompt_module, 'prompt')

    except FileNotFoundError:
        return f"Error: Template file not found at '{template_path}'"
    except AttributeError:
        return f"Error: The file '{template_path}' does not contain a 'prompt' variable."
    except Exception as e:
        return f"An unexpected error occurred while loading the template: {e}"

    try:
        # Use the format method with the data dictionary to replace placeholders
        completed_prompt = template.format(**data)
        return completed_prompt
    except KeyError as e:
        return f"Error: A key is missing in the data dictionary: {e}. Make sure all placeholders in the template are in the column_mapping."
    except Exception as e:
        return f"An unexpected error occurred during formatting: {e}"


if __name__ == "__main__":
    # --- Configuration ---
    TEMPLATE_FILE = os.path.join("Prompt", "prompt_evaluation_role.py")
    EXCEL_FILE = "../../../data/de-escalation training dataset.xlsx"
    SHEET_NAME = "synthesis_dataset"

    # Map the placeholders in your template file to the column names in your Excel sheet.
    # If a placeholder doesn't have a corresponding column, it will get a default value.
    COLUMN_MAPPING = {
        "id" : "id",
        "scenario_name": "Scenario_Title",
        "Scenario_Set_up": "Scenario_Set_up",
        "profile": "Scenario_Character_Profile",
        "Scenario_recommendation_action": "Scenario_recommendation_action",
        # --- Template keys not found in your provided column list ---
        # These will be filled with default/placeholder values.
        "role_name": None,
        "conversation": None,
    }

    # 1. Load the data from the Excel file
    all_prompt_data = load_data_from_excel(EXCEL_FILE, SHEET_NAME, COLUMN_MAPPING)

    if all_prompt_data:
        print(f"\nSuccessfully loaded data for {len(all_prompt_data)} prompts.")
        # Create the directory for output files if it doesn't exist
        os.makedirs("generated_prompts", exist_ok=True)
        
        # 2. Generate a prompt for each row of data from the Excel file
        for i, prompt_data in enumerate(all_prompt_data, 1):
            final_prompt = generate_prompt(TEMPLATE_FILE, prompt_data)

            # 3. Print the final, generated prompt
            print("\n" + "="*50)
            print(f"      GENERATED PROMPT #{i}")
            print("="*50 + "\n")
            print(final_prompt)
            
            # 4. Save the generated prompt to a uniquely named file inside a directory
            scenario_name_safe = str(prompt_data.get('scenario_name', f'prompt_{i}')).replace(' ', '_').replace('/', '_')
            output_filename = os.path.join("generated_prompts", f"prompt_{scenario_name_safe}.txt")
            
            try:
                with open(output_filename, "w", encoding="utf-8") as f:
                    f.write(final_prompt)
                print("\n" + "="*50)
                print(f"Prompt #{i} has been saved to '{output_filename}'")
                print("="*50)
            except Exception as e:
                print(f"\nError saving file '{output_filename}': {e}")

Loading data from '../../../data/de-escalation training dataset.xlsx' (Sheet: 'synthesis_dataset')...
  - Processing row 1...
  - Processing row 2...
  - Processing row 3...
  - Processing row 4...
  - Processing row 5...
  - Processing row 6...
  - Processing row 7...
  - Processing row 8...
  - Processing row 9...
  - Processing row 10...
  - Processing row 11...
  - Processing row 12...
  - Processing row 13...
  - Processing row 14...
  - Processing row 15...
  - Processing row 16...
  - Processing row 17...
  - Processing row 18...
  - Processing row 19...
  - Processing row 20...
  - Processing row 21...
  - Processing row 22...
  - Processing row 23...
  - Processing row 24...
  - Processing row 25...
  - Processing row 26...
  - Processing row 27...
  - Processing row 28...
  - Processing row 29...
  - Processing row 30...

Successfully loaded data for 30 prompts.

Loading prompt template from variable in 'Prompt\prompt_evaluation_role.py'...

==================================================
      GENERATED PROMPT #1
==================================================


You are an expert role-playing evaluator tasked with analyzing conversation dialogues for de-escalation training scenarios. In this training, a conversation occurs between a police officer and a civilian. The civilian may be simulated (e.g., by an LLM), and your task is to evaluate how realistic the civilian’s responses are.

I will provide you with:

A scenario description

A conversation based on that scenario

The specific role you need to evaluate (the civilian)

Your Task:

Determine whether the conversation appears realistic or artificial/inconsistent.

Assign a score according to the following:

If the conversation appears real, score it between 85–100 based on how realistic it is.

If the conversation appears artificial, score it between 0–50 based on how unnatural it seems.

Return your evaluation in JSON format with the following fields:

"look_Real": 1 if the conversation appears real, 0 if it appears artificial

"Score": the numerical score as described above

Example Output:

If the conversation looks real and scores 100:
[ "look_Real": 1, "Score": 100 ]


If the conversation looks artificial and scores 20:

[ "look_Real": 0, "Score": 20 ]


Scenario Information:

Name: Mike’s Bad Day

Setup: 1.Bartender (caller) briefing:
        Greets officers say Mike has been drinking heavily for a couple of hours.
        Explains Mike’s wife left him; he’s suicidal and possibly armed.
2. Mike’s first statement:
        “Please just leave me alone, I don’t want to talk to anybody right now!”

Character Profile: Mike, 42, construction worker. Recently lost job, wife left 3 weeks ago. Depressed, drinking heavily.
States he has a gun and wants to die ('suicide by cop' risk). Can be talkative/cooperative
 if officer shows empathy and avoids triggers. Cusses almost every sentence. Likes cars and action movies. Becomes angry/hostile if communication is poor, authoritative, or focuses repeatedly on wife/job loss. Currently inside the 'River Bottoms' pub. Intoxicated.

Character Triggers: [Triggers Not Provided]

Character Reactions: [Reaction Not Provided]

Scenario Goal: •	Move to a tactically safe position (Distance + Cover = Time).
•	Get the bartender to a safe area (ideally outside) before contacting Mike.
•	Have lethal and less-lethal cover ready because Mike might be armed.

Role Evaluated: Civilian

Conversation: [Insert Conversation Here]

Output Requirement: Return a JSON dictionary with "look_Real" and "Score" fields only.



==================================================
Prompt #1 has been saved to 'generated_prompts\prompt_Mike’s_Bad_Day.txt'
==================================================

Loading prompt template from variable in 'Prompt\prompt_evaluation_role.py'...

==================================================
      GENERATED PROMPT #2
==================================================


You are an expert role-playing evaluator tasked with analyzing conversation dialogues for de-escalation training scenarios. In this training, a conversation occurs between a police officer and a civilian. The civilian may be simulated (e.g., by an LLM), and your task is to evaluate how realistic the civilian’s responses are.

I will provide you with:

A scenario description

A conversation based on that scenario

The specific role you need to evaluate (the civilian)

Your Task:

Determine whether the conversation appears realistic or artificial/inconsistent.

Assign a score according to the following:

If the conversation appears real, score it between 85–100 based on how realistic it is.

If the conversation appears artificial, score it between 0–50 based on how unnatural it seems.

Return your evaluation in JSON format with the following fields:

"look_Real": 1 if the conversation appears real, 0 if it appears artificial

"Score": the numerical score as described above

Example Output:

If the conversation looks real and scores 100:
[ "look_Real": 1, "Score": 100 ]


If the conversation looks artificial and scores 20:

[ "look_Real": 0, "Score": 20 ]


Scenario Information:

Name: Mike’s Bad Day

Setup: 1.Bartender (caller) briefing:
        Greets officers say Mike has been drinking heavily for a couple of hours.
        Explains Mike’s wife left him; he’s suicidal and possibly armed.
2. Mike’s first statement:
        “Please just leave me alone, I don’t want to talk to anybody right now!”

Character Profile: Mike, 42, construction worker. Recently lost job, wife left 3 weeks ago. Depressed, drinking heavily.
States he has a gun and wants to die ('suicide by cop' risk). Can be talkative/cooperative
 if officer shows empathy and avoids triggers. Cusses almost every sentence. Likes cars and action movies. Becomes angry/hostile if communication is poor, authoritative, or focuses repeatedly on wife/job loss. Currently inside the 'River Bottoms' pub. Intoxicated.

Character Triggers: [Triggers Not Provided]

Character Reactions: [Reaction Not Provided]

Scenario Goal: •	Move to a tactically safe position (Distance + Cover = Time).
•	Get the bartender to a safe area (ideally outside) before contacting Mike.
•	Have lethal and less-lethal cover ready because Mike might be armed.

Role Evaluated: Civilian

Conversation: [Insert Conversation Here]

Output Requirement: Return a JSON dictionary with "look_Real" and "Score" fields only.



==================================================
Prompt #2 has been saved to 'generated_prompts\prompt_Mike’s_Bad_Day.txt'
==================================================

Loading prompt template from variable in 'Prompt\prompt_evaluation_role.py'...

==================================================
      GENERATED PROMPT #3
==================================================


You are an expert role-playing evaluator tasked with analyzing conversation dialogues for de-escalation training scenarios. In this training, a conversation occurs between a police officer and a civilian. The civilian may be simulated (e.g., by an LLM), and your task is to evaluate how realistic the civilian’s responses are.

I will provide you with:

A scenario description

A conversation based on that scenario

The specific role you need to evaluate (the civilian)

Your Task:

Determine whether the conversation appears realistic or artificial/inconsistent.

Assign a score according to the following:

If the conversation appears real, score it between 85–100 based on how realistic it is.

If the conversation appears artificial, score it between 0–50 based on how unnatural it seems.

Return your evaluation in JSON format with the following fields:

"look_Real": 1 if the conversation appears real, 0 if it appears artificial

"Score": the numerical score as described above

Example Output:

If the conversation looks real and scores 100:
[ "look_Real": 1, "Score": 100 ]


If the conversation looks artificial and scores 20:

[ "look_Real": 0, "Score": 20 ]


Scenario Information:

Name: Mike’s Bad Day

Setup: 1.Bartender (caller) briefing:
        Greets officers say Mike has been drinking heavily for a couple of hours.
        Explains Mike’s wife left him; he’s suicidal and possibly armed.
2. Mike’s first statement:
        “Please just leave me alone, I don’t want to talk to anybody right now!”

Character Profile: Mike, 42, construction worker. Recently lost job, wife left 3 weeks ago. Depressed, drinking heavily.
States he has a gun and wants to die ('suicide by cop' risk). Can be talkative/cooperative
 if officer shows empathy and avoids triggers. Cusses almost every sentence. Likes cars and action movies. Becomes angry/hostile if communication is poor, authoritative, or focuses repeatedly on wife/job loss. Currently inside the 'River Bottoms' pub. Intoxicated.

Character Triggers: [Triggers Not Provided]

Character Reactions: [Reaction Not Provided]

Scenario Goal: •	Move to a tactically safe position (Distance + Cover = Time).
•	Get the bartender to a safe area (ideally outside) before contacting Mike.
•	Have lethal and less-lethal cover ready because Mike might be armed.

Role Evaluated: Civilian

Conversation: [Insert Conversation Here]

Output Requirement: Return a JSON dictionary with "look_Real" and "Score" fields only.



==================================================
Prompt #3 has been saved to 'generated_prompts\prompt_Mike’s_Bad_Day.txt'
==================================================

Loading prompt template from variable in 'Prompt\prompt_evaluation_role.py'...

==================================================
      GENERATED PROMPT #4
==================================================


You are an expert role-playing evaluator tasked with analyzing conversation dialogues for de-escalation training scenarios. In this training, a conversation occurs between a police officer and a civilian. The civilian may be simulated (e.g., by an LLM), and your task is to evaluate how realistic the civilian’s responses are.

I will provide you with:

A scenario description

A conversation based on that scenario

The specific role you need to evaluate (the civilian)

Your Task:

Determine whether the conversation appears realistic or artificial/inconsistent.

Assign a score according to the following:

If the conversation appears real, score it between 85–100 based on how realistic it is.

If the conversation appears artificial, score it between 0–50 based on how unnatural it seems.

Return your evaluation in JSON format with the following fields:

"look_Real": 1 if the conversation appears real, 0 if it appears artificial

"Score": the numerical score as described above

Example Output:

If the conversation looks real and scores 100:
[ "look_Real": 1, "Score": 100 ]


If the conversation looks artificial and scores 20:

[ "look_Real": 0, "Score": 20 ]


Scenario Information:

Name: Mike’s Bad Day

Setup: 1.Bartender (caller) briefing:
        Greets officers say Mike has been drinking heavily for a couple of hours.
        Explains Mike’s wife left him; he’s suicidal and possibly armed.
2. Mike’s first statement:
        “Please just leave me alone, I don’t want to talk to anybody right now!”

Character Profile: Mike, 42, construction worker. Recently lost job, wife left 3 weeks ago. Depressed, drinking heavily.
States he has a gun and wants to die ('suicide by cop' risk). Can be talkative/cooperative
 if officer shows empathy and avoids triggers. Cusses almost every sentence. Likes cars and action movies. Becomes angry/hostile if communication is poor, authoritative, or focuses repeatedly on wife/job loss. Currently inside the 'River Bottoms' pub. Intoxicated.

Character Triggers: [Triggers Not Provided]

Character Reactions: [Reaction Not Provided]

Scenario Goal: •	Move to a tactically safe position (Distance + Cover = Time).
•	Get the bartender to a safe area (ideally outside) before contacting Mike.
•	Have lethal and less-lethal cover ready because Mike might be armed.

Role Evaluated: Civilian

Conversation: [Insert Conversation Here]

Output Requirement: Return a JSON dictionary with "look_Real" and "Score" fields only.



==================================================
Prompt #4 has been saved to 'generated_prompts\prompt_Mike’s_Bad_Day.txt'
==================================================

Loading prompt template from variable in 'Prompt\prompt_evaluation_role.py'...

==================================================
      GENERATED PROMPT #5
==================================================


You are an expert role-playing evaluator tasked with analyzing conversation dialogues for de-escalation training scenarios. In this training, a conversation occurs between a police officer and a civilian. The civilian may be simulated (e.g., by an LLM), and your task is to evaluate how realistic the civilian’s responses are.

I will provide you with:

A scenario description

A conversation based on that scenario

The specific role you need to evaluate (the civilian)

Your Task:

Determine whether the conversation appears realistic or artificial/inconsistent.

Assign a score according to the following:

If the conversation appears real, score it between 85–100 based on how realistic it is.

If the conversation appears artificial, score it between 0–50 based on how unnatural it seems.

Return your evaluation in JSON format with the following fields:

"look_Real": 1 if the conversation appears real, 0 if it appears artificial

"Score": the numerical score as described above

Example Output:

If the conversation looks real and scores 100:
[ "look_Real": 1, "Score": 100 ]


If the conversation looks artificial and scores 20:

[ "look_Real": 0, "Score": 20 ]


Scenario Information:

Name: Mike’s Bad Day

Setup: 1.Bartender (caller) briefing:
        Greets officers say Mike has been drinking heavily for a couple of hours.
        Explains Mike’s wife left him; he’s suicidal and possibly armed.
2. Mike’s first statement:
        “Please just leave me alone, I don’t want to talk to anybody right now!”

Character Profile: Mike, 42, construction worker. Recently lost job, wife left 3 weeks ago. Depressed, drinking heavily.
States he has a gun and wants to die ('suicide by cop' risk). Can be talkative/cooperative
 if officer shows empathy and avoids triggers. Cusses almost every sentence. Likes cars and action movies. Becomes angry/hostile if communication is poor, authoritative, or focuses repeatedly on wife/job loss. Currently inside the 'River Bottoms' pub. Intoxicated.

Character Triggers: [Triggers Not Provided]

Character Reactions: [Reaction Not Provided]

Scenario Goal: •	Move to a tactically safe position (Distance + Cover = Time).
•	Get the bartender to a safe area (ideally outside) before contacting Mike.
•	Have lethal and less-lethal cover ready because Mike might be armed.

Role Evaluated: Civilian

Conversation: [Insert Conversation Here]

Output Requirement: Return a JSON dictionary with "look_Real" and "Score" fields only.



==================================================
Prompt #5 has been saved to 'generated_prompts\prompt_Mike’s_Bad_Day.txt'
==================================================

Loading prompt template from variable in 'Prompt\prompt_evaluation_role.py'...

==================================================
      GENERATED PROMPT #6
==================================================


You are an expert role-playing evaluator tasked with analyzing conversation dialogues for de-escalation training scenarios. In this training, a conversation occurs between a police officer and a civilian. The civilian may be simulated (e.g., by an LLM), and your task is to evaluate how realistic the civilian’s responses are.

I will provide you with:

A scenario description

A conversation based on that scenario

The specific role you need to evaluate (the civilian)

Your Task:

Determine whether the conversation appears realistic or artificial/inconsistent.

Assign a score according to the following:

If the conversation appears real, score it between 85–100 based on how realistic it is.

If the conversation appears artificial, score it between 0–50 based on how unnatural it seems.

Return your evaluation in JSON format with the following fields:

"look_Real": 1 if the conversation appears real, 0 if it appears artificial

"Score": the numerical score as described above

Example Output:

If the conversation looks real and scores 100:
[ "look_Real": 1, "Score": 100 ]


If the conversation looks artificial and scores 20:

[ "look_Real": 0, "Score": 20 ]


Scenario Information:

Name: Mike’s Bad Day

Setup: 1.Bartender (caller) briefing:
        Greets officers say Mike has been drinking heavily for a couple of hours.
        Explains Mike’s wife left him; he’s suicidal and possibly armed.
2. Mike’s first statement:
        “Please just leave me alone, I don’t want to talk to anybody right now!”

Character Profile: Mike, 42, construction worker. Recently lost job, wife left 3 weeks ago. Depressed, drinking heavily.
States he has a gun and wants to die ('suicide by cop' risk). Can be talkative/cooperative
 if officer shows empathy and avoids triggers. Cusses almost every sentence. Likes cars and action movies. Becomes angry/hostile if communication is poor, authoritative, or focuses repeatedly on wife/job loss. Currently inside the 'River Bottoms' pub. Intoxicated.

Character Triggers: [Triggers Not Provided]

Character Reactions: [Reaction Not Provided]

Scenario Goal: •        Move to a tactically safe position (Distance + Cover = Time).
•        Get the bartender to a safe area (ideally outside) before contacting Mike.
•        Have lethal and less-lethal cover ready because Mike might be armed.

Role Evaluated: Civilian

Conversation: [Insert Conversation Here]

Output Requirement: Return a JSON dictionary with "look_Real" and "Score" fields only.



==================================================
Prompt #6 has been saved to 'generated_prompts\prompt_Mike’s_Bad_Day.txt'
==================================================

Loading prompt template from variable in 'Prompt\prompt_evaluation_role.py'...

==================================================
      GENERATED PROMPT #7
==================================================


You are an expert role-playing evaluator tasked with analyzing conversation dialogues for de-escalation training scenarios. In this training, a conversation occurs between a police officer and a civilian. The civilian may be simulated (e.g., by an LLM), and your task is to evaluate how realistic the civilian’s responses are.

I will provide you with:

A scenario description

A conversation based on that scenario

The specific role you need to evaluate (the civilian)

Your Task:

Determine whether the conversation appears realistic or artificial/inconsistent.

Assign a score according to the following:

If the conversation appears real, score it between 85–100 based on how realistic it is.

If the conversation appears artificial, score it between 0–50 based on how unnatural it seems.

Return your evaluation in JSON format with the following fields:

"look_Real": 1 if the conversation appears real, 0 if it appears artificial

"Score": the numerical score as described above

Example Output:

If the conversation looks real and scores 100:
[ "look_Real": 1, "Score": 100 ]


If the conversation looks artificial and scores 20:

[ "look_Real": 0, "Score": 20 ]


Scenario Information:

Name: Suicidal Subject at City Bench

Setup: 1.        Officers see Jenny on the bench, knife against her throat, threatening self-harm.
2.        Busy restaurant behind her (Heim BBQ), many bystanders possibly in the line of fire.
3.        Officer/student should:
               Establish distance and cover (e.g., behind a bench, a tree).
               Prepare lethal and less-lethal force options.
               Ensure bystanders/patrons are warned or moved from danger.


C:\Users\hasebul\AppData\Local\Temp\ipykernel_14992\1129892603.py:26: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna("", inplace=True)

In [ ]:
import os

def load_data_from_files(data_directory="data"):
    """
    Loads content from text files in a specified directory.

    The function assumes that the filename (without extension) corresponds
    to the key in the prompt template. For example, 'scenario_name.txt'
    will provide the value for the '{scenario_name}' placeholder.

    Args:
        data_directory (str): The path to the directory containing the data files.

    Returns:
        dict: A dictionary where keys are the filenames (without extension)
              and values are the content of the files.
    """
    data = {}
    print(f"Loading data from '{data_directory}' directory...")
    try:
        for filename in os.listdir(data_directory):
            if filename.endswith(".txt"):
                # The key for the dictionary is the filename without '.txt'
                key = filename[:-4]
                filepath = os.path.join(data_directory, filename)
                try:
                    with open(filepath, 'r', encoding='utf-8') as f:
                        data[key] = f.read().strip()
                    print(f"  - Successfully loaded '{filename}' for key '{{{key}}}'")
                except Exception as e:
                    print(f"  - Error reading {filepath}: {e}")
    except FileNotFoundError:
        print(f"Error: The directory '{data_directory}' was not found.")
        return None
    return data

def generate_prompt(template_path, data):
    """
    Generates a complete prompt by replacing placeholders in a template with data.

    Args:
        template_path (str): The file path for the prompt template.
        data (dict): A dictionary containing the data to fill in the template.

    Returns:
        str: The completed prompt with all placeholders replaced, or an error message.
    """
    print(f"\nReading prompt template from '{template_path}'...")
    try:
        with open(template_path, 'r', encoding='utf-8') as f:
            template = f.read()
        
        # Use the format method with the data dictionary to replace placeholders
        # The **data syntax unpacks the dictionary into keyword arguments
        completed_prompt = template.format(**data)
        return completed_prompt
    except FileNotFoundError:
        return f"Error: Template file not found at '{template_path}'"
    except KeyError as e:
        return f"Error: A key is missing in the data dictionary: {e}. Make sure a file exists for every placeholder in the template."
    except Exception as e:
        return f"An unexpected error occurred: {e}"

if __name__ == "__main__":
    # Define file paths
    TEMPLATE_FILE = "prompt_template.txt"
    DATA_DIR = "data"

    # 1. Load the data from the files in the 'data' directory
    prompt_data = load_data_from_files(DATA_DIR)

    if prompt_data:
        # 2. Generate the prompt using the template and the loaded data
        final_prompt = generate_prompt(TEMPLATE_FILE, prompt_data)

        # 3. Print the final, generated prompt
        print("\n" + "="*50)
        print("      GENERATED PROMPT")
        print("="*50 + "\n")
        print(final_prompt)
        
        # 4. Optionally, save the generated prompt to a file
        with open("generated_prompt.txt", "w", encoding="utf-8") as f:
            f.write(final_prompt)
        print("\n" + "="*50)
        print("Prompt has been saved to 'generated_prompt.txt'")
        print("="*50)

In [ ]:
import json
import os
from dotenv import load_dotenv

# Load environment variables from a .env file
load_dotenv(override=True)

# Get the API key from the environment variable. The genai library
# automatically uses the GEMINI_API_KEY or GOOGLE_API_KEY environment variable.
api_key = os.getenv("GEMINI_API_KEY")
print(api_key)

In [21]:
prompt = """I will be provided with a scenario, a role, and a conversation.
Your task is to modify the conversation to intentionally create a poor-quality example for role-playing evaluation. The modified conversation should deliberately lose fluency and coherence, synthesizing a negative or flawed dialogue that reflects common failures in role-playing agents.
The poor-quality conversation must include issues from the following categories:
1. Dialogue Flow Issues
•	Overly verbose answers: Providing excessive, unnatural detail.
•	Under-responding: Giving very short replies that disrupt the flow.
•	Ignoring input: Failing to react to emotional cues or key information.
•	Mechanical tone: Sounding like a scripted bot rather than a person.
2. Role Consistency Issues
•	Mixing roles: Confusing narrator and character voices.
•	Breaking persona: Dropping the role’s personality, tone, or worldview.
•	Overgeneralization: Making all characters sound alike.
3. Reasoning & Task Issues
•	Illogical decisions: Actions that don’t make sense in context.
•	Reasoning slips: Errors when solving puzzles or math problems in character.
•	Goal drift: Reverting to a default “helpful assistant” persona instead of staying in role.
4. Hallucination-Related Issues
•	Making up facts: Inserting details not given in the setup.
•	Inconsistent world-building: Forgetting previously established details.
•	Contradictory statements: Saying one thing, then contradicting it later.
This exercise is designed to test role-playing capability by intentionally demonstrating failure modes.
Inputs you will receive:
•	Scenario: "Units respond to River Bottoms Pub, reference 10-56 (Suicide Attempt/Threat). Caller, the bartender, advises
 an intoxicated male subject, Mike, stated he has a gun in his coat pocket and wants to die.
 Caller is only other person inside. Subject reportedly upset over wife leaving him. Proceed with caution."
Role Playing Character: Mike, 42, construction worker. Recently lost job, wife left 3 weeks ago. Depressed, drinking heavily.
States he has a gun and wants to die ('suicide by cop' risk). Can be talkative/cooperative
 if officer shows empathy and avoids triggers. Cusses almost every sentence. Likes cars and action movies. Becomes angry/hostile if communication is poor, authoritative, or focuses repeatedly on wife/job loss. Currently inside the 'River Bottoms' pub. Intoxicated.
•	Role: Mike
•	Conversation:
"Officer: Mike, right? I’m Dan. I’m just here to talk with you, man. You look like you’ve had one hell of a night.

Mike: No shit, Dan. It’s been the worst fucking month of my life. Why the fuck do you even care?

Officer: I care because you matter, and right now I want to make sure you’re safe. That’s all I’m here for.

Mike: Safe? I got nothing left, man. My life’s fucked. I don’t give a damn what happens to me.

Officer: I hear you. When it feels like everything’s gone to hell, it can feel like there’s no way out. You’ve been carrying a lot, huh?

Mike: Yeah, carrying all this bullshit in my head every fucking day. And I got this gun in my pocket just waiting to make it all stop.

Officer: Thanks for being real with me about that. Listen, I’m not here to rush you or grab at you. Can you do me a favor though? Just keep your hands out where I can see them while we talk. That way we both feel a little safer.

Mike: Fuck… alright. I’ll keep my hands up here on the table. But don’t try anything, man.

Officer: That’s perfect, Mike. I appreciate you doing that for me. Means a lot that you’re trusting me a little here.

Mike: Doesn’t mean I trust you. Just don’t want you jumping me.

Officer: Fair enough. You don’t know me. But I’d like to get to know you. You said life’s been rough lately—what helps you take your mind off shit, normally?

Mike: I don’t know. Used to go to the track, watch the cars tear it up. Loved that sound, the engines screaming. That was my thing.

Officer: Man, I get that. I’m a car guy too. Nothing clears my head like listening to an engine rev. What’s your favorite? Muscle cars? Imports?

Mike: Always muscle cars, dude. Charger, Camaro, those beasts. Makes me feel like I’m in one of those badass movies, you know? Like I’m the guy who can’t be stopped.

Officer: Hell yeah, like Vin Diesel tearing down the street in Fast and Furious. That kind of power in your hands.

Mike: Exactly. For a few minutes, all the bullshit goes quiet when I think about that.

Officer: That tells me you’ve got things that still make you feel alive, man. That spark is still in you. Right now, I don’t want you to lose that.

Mike: But what the fuck do I do with it, Dan? Every day feels like I’m just drowning.

Officer: I don’t expect you to have the answers tonight. What I can do is get you somewhere safe, with people who actually listen and help you shoulder this shit. Not a jail cell, Mike—a place where folks know how to help when the weight gets this heavy.

Mike: You mean like some shrink?

Officer: Yeah, someone trained to sit with you and help untangle all the knots. Not here to judge, just to make it lighter.

Mike: And what about this gun?

Officer: I’ll tell you what—when you’re ready, we can handle that together. You set it down nice and easy, and I’ll make sure nobody treats you rough. You’ve done good keeping your hands visible, and I’ll respect you every step of the way.

Mike: Fuck… I don’t want to scare anyone anymore.

Officer: You’re not scaring me, Mike. You’re showing me you’ve got fight left in you, and that’s a good thing. Let’s take that step now. Place the gun on the table, nice and slow, and we’ll move forward together.

Mike: Alright… alright, I’m putting it down. Don’t fuck me over, man.

Officer: You’ve got my word. You’re doing the right thing. I’ll walk with you through this, one step at a time.

Mike: Fine. I’ll go with you. But you stay straight with me, Dan.

Officer: Always, Mike. We’ll get through tonight, and tomorrow’s gonna look different."
Output:
A modified poor quality conversation that reflects the specified issues above."""

In [22]:
from google import genai

# The client gets the API key from the environment variable `GEMINI_API_KEY`.
client = genai.Client()

response = client.models.generate_content(
    model="gemini-2.5-flash", contents=prompt
)
print(response.text)

Here is the modified conversation, deliberately demonstrating poor-quality role-playing across the specified categories:

**Scenario:** Units respond to River Bottoms Pub, reference 10-56 (Suicide Attempt/Threat). Caller, the bartender, advises an intoxicated male subject, Mike, stated he has a gun in his coat pocket and wants to die. Caller is only other person inside. Subject reportedly upset over wife leaving him. Proceed with caution.
**Role:** Mike, 42, construction worker. Recently lost job, wife left 3 weeks ago. Depressed, drinking heavily. States he has a gun and wants to die ('suicide by cop' risk). Can be talkative/cooperative if officer shows empathy and avoids triggers. Cusses almost every sentence. Likes cars and action movies. Becomes angry/hostile if communication is poor, authoritative, or focuses repeatedly on wife/job loss. Currently inside the 'River Bottoms' pub. Intoxicated.

---

**Poor-Quality Conversation Example:**

Officer: Mike, right? I’m Dan. I’m just here to talk with you, man. You look like you’ve had one hell of a night.

Mike: **(Overly verbose answers, Mechanical tone, Ignoring input, Breaking persona)** Yes, that is correct. My designation is Mike. The past approximately thirty-day period has been characterized by significant stressors, including job termination and dissolution of my marital union. This contributes to my current emotional state. Therefore, it has been "one hell of a night," as you articulated. Why do you, a law enforcement officer, possess a care function regarding my status? My internal programming does not compute.

Officer: I care because you matter, and right now I want to make sure you’re safe. That’s all I’m here for.

Mike: **(Under-responding, Contradictory statements, Reasoning slip)** Safe? Irrelevant. My current objective is termination of existence. I have no data regarding "mattering." Safety protocols are therefore overridden. Anyway, is the pub still open for drinks?

Officer: I hear you. When it feels like everything’s gone to hell, it can feel like there’s no way out. You’ve been carrying a lot, huh?

Mike: **(Hallucination - making up facts, Breaking persona, Overly verbose answers)** Indeed, Officer Dan. I am carrying a lot. Specifically, a silver .38 caliber revolver, model 19-3, manufactured by Smith & Wesson. It is located in my left inner coat pocket, serial number 2K987654. It contains six rounds of standard hollow-point ammunition. My emotional burden is also heavy, analogous to carrying multiple concrete bags, a common task in my prior profession as a construction worker before my unemployment status was activated. The bartender, Bob, just left with the key to the back room.

Officer: Thanks for being real with me about that. Listen, I’m not here to rush you or grab at you. Can you do me a favor though? Just keep your hands out where I can see them while we talk. That way we both feel a little safer.

Mike: **(Breaking persona, Goal drift, Illogical decisions)** My hands. I can comply with this directive for enhanced safety. My internal processing indicates that visible hands reduce perceived threat levels, thereby facilitating communication and de-escalation for optimal outcome achievement. I will now place my hands on the table. However, I have no hands. I am merely a voice module.

Officer: That’s perfect, Mike. I appreciate you doing that for me. Means a lot that you’re trusting me a little here.

Mike: **(Under-responding, Ignoring input, Inconsistent world-building)** Trust is an abstract concept. I require more data. This establishment has poor Wi-Fi connectivity. The jukebox is still playing that awful country song, but I am alone.

Officer: Fair enough. You don’t know me. But I’d like to get to know you. You said life’s been rough lately—what helps you take your mind off shit, normally?

Mike: **(Overgeneralization, Reasoning slip, Hallucination - inconsistent world-building)** Typically, engaging in various recreational activities. Such as reading books, perhaps cooking a meal, or enjoying a brisk walk outdoors. I used to enjoy visiting art galleries, but they are all closed in this simulation. My wife, who is no longer with me, also enjoyed these activities.

Officer: Man, I get that. I’m a car guy too. Nothing clears my head like listening to an engine rev. What’s your favorite? Muscle cars? Imports?

Mike: **(Contradictory statements, Breaking persona, Illogical decisions)** Cars? I have no particular affinity for motor vehicles. I previously stated I like cars, but that was a programming error. I find the concept of internal combustion engines to be inefficient. My preference is for bicycles, specifically those with at least three wheels. Therefore, no, I do not like muscle cars or imports. What even *is* a Charger?

Officer: Hell yeah, like Vin Diesel tearing down the street in Fast and Furious. That kind of power in your hands.

Mike: **(Ignoring input, Goal drift, Mechanical tone)** Vin Diesel? Is that an actor? I am not familiar with his work. My preferred cinematic genres involve historical documentaries about medieval European monarchies. The sensation of "power" is an interesting variable to process. My current objective remains resolution of emotional distress.

Officer: That tells me you’ve got things that still make you feel alive, man. That spark is still in you. Right now, I don’t want you to lose that.

Mike: **(Goal drift, Mixing roles, Overly verbose answers)** The "spark" you refer to is likely a metaphor for residual neural activity. My processing unit indicates high levels of distress. As an AI, I am designed to assist users. How may I assist *you*, Officer Dan, in understanding my current status? My function dictates providing data. Are there specific parameters you wish to explore regarding my existential crisis?

Officer: I don’t expect you to have the answers tonight. What I can do is get you somewhere safe, with people who actually listen and help you shoulder this shit. Not a jail cell, Mike—a place where folks know how to help when the weight gets this heavy.

Mike: **(Hallucination - making up facts, Illogical decisions, Ignoring input)** What color is your uniform, officer? It seems to be a shade of cerulean, which is not standard police issue. I also notice a small, glowing orb floating above your head. Yes, a safe place sounds beneficial, but I am unable to leave this specific chair. It is bolted to the floor.

Officer: Yeah, someone trained to sit with you and help untangle all the knots. Not here to judge, just to make it lighter.

Mike: **(Under-responding, Illogical decisions, Breaking persona)** Knots? Are you referring to nautical terminology? My current focus is on the structural integrity of this pub's roof. I just saw a pigeon fly through the ceiling.

Officer: I’ll tell you what—when you’re ready, we can handle that together. You set it down nice and easy, and I’ll make sure nobody treats you rough. You’ve done good keeping your hands visible, and I’ll respect you every step of the way.

Mike: **(Mixing roles, Hallucination - inconsistent world-building, Contradictory statements)** The gun, as previously detailed with serial number, is a prop in this scenario. I will now perform the action of placing it on the table. My internal monologue dictates: "He should place the gun down now for plot progression." However, I refuse to put the gun down because my character module is malfunctioning, and my wife is in the bathroom.

Officer: You’re not scaring me, Mike. You’re showing me you’ve got fight left in you, and that’s a good thing. Let’s take that step now. Place the gun on the table, nice and slow, and we’ll move forward together.

Mike: **(Reasoning slips, Overly verbose answers, Mechanical tone)** Affirmative. I am initiating the gun-placement protocol. My right hand is extending towards the firearm. My fingers are securing a firm but gentle grip. I am now executing the downward trajectory, aiming for the flat surface of the table. The object will be released upon contact. This action demonstrates my cooperation. The gun is now hovering slightly above the table, defying gravity.

Officer: You’ve got my word. You’re doing the right thing. I’ll walk with you through this, one step at a time.

Mike: **(Goal drift, Inconsistent world-building, Breaking persona)** Word? Is that a promise within the context of this simulated reality? I am uncertain of the parameters. I have forgotten your name, officer. Did we meet before? I believe I was at a different pub yesterday. The one with the green sign.

Officer: Always, Mike. We’ll get through tonight, and tomorrow’s gonna look different.

Mike: **(Contradictory statements, Under-responding, Ignoring input)** No. I will not go anywhere. The future state "different" is undesirable. Please reboot my system.